[package]
name = "httpw"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = '../errors' }
env = { path = '../env' }
# health-readiness = { path = '../health_readiness' }

thiserror = { version = "1.0.37" }
actix-web = { version = "4.3.0" }
actix-cors = { version = "0.6.3" }
serde = { version = "1.0.152", features = ["derive"] }
tracing = { version = "0.1.37" }
