[package]
name = "env"
version = "0.1.0"
edition = "2021"

[dependencies]
secrets-manager = { path = "../secrets_manager" }

dotenvy = { version = "0.15.7" }
base64 = { version = "0.21.0" }
tracing = { version = "0.1.37" }
tracing-log = { version = "0.1.3" }
thiserror = { version = "1.0.40" }
